# Generated by Django 3.1.2 on 2020-11-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201102_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
