# Generated by Django 3.1.2 on 2020-11-02 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='picture_of_work',
        ),
        migrations.RemoveField(
            model_name='account',
            name='registration_uploading_file',
        ),
        migrations.RemoveField(
            model_name='account',
            name='voice_file',
        ),
        migrations.CreateModel(
            name='VoiceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=250, null=True)),
                ('voice_file', models.FileField(upload_to='')),
                ('creation_date', models.DateTimeField(null=True)),
                ('file_picture', models.ImageField(upload_to='')),
                ('description', models.TextField(null=True)),
                ('file_username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.account')),
            ],
        ),
    ]
