# Generated by Django 3.1.2 on 2020-11-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20201123_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email_address',
            field=models.CharField(error_messages={'unique': 'This email address has been taken'}, max_length=250, null=True, unique=True),
        ),
    ]
